{
 "title": "CC_Project",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "All Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time,\n  endpoint,\n  method,\n  path,\n  client_ip,\n  status_code,\n  response_time_ms,\n  user_agent\nFROM \n  logs\nORDER BY \n  timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_requests FROM logs;"
    }
   ]
  },
  {
   "title": "Average Response Time Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time, \n  AVG(response_time_ms) AS avg_response_time \nFROM logs \nGROUP BY time \nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Requests Per Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \n  endpoint, \n  COUNT(*) AS request_count\nFROM \n  logs \nGROUP BY \n  endpoint\nORDER BY \n  request_count DESC;\n"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN status_code = 500 THEN 'Internal Server Error'\n    WHEN status_code = 404 THEN 'Not Found'\n    WHEN status_code = 422 THEN 'Unprocessable Entity'\n  END AS error_type,\n  COUNT(*) AS count \nFROM logs\nWHERE status_code IN (500, 404, 422)\nGROUP BY error_type;\n"
    }
   ]
  },
  {
   "title": "Slowest Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  endpoint, \n  AVG(response_time_ms) AS avg_response_time \nFROM logs \nGROUP BY endpoint \nORDER BY avg_response_time DESC \nLIMIT 5;\n"
    }
   ]
  }
 ]
}